apiVersion: v1
kind: Pod
metadata:
  name: pillow
spec:
  containers:
    - name: pillow
      command:
        - "/bin/bash"
        - "-i"
      image: r00tus3r/base-runner
      imagePullPolicy: Always
      stdin: true
      tty: true
      volumeMounts:
        - name: nfs
          mountPath: "/shared"
      resources:
        limits:
          cpu: 1000m
          memory: 4Gi
        requests:
          cpu: 900m
          memory: 2Gi
      securityContext:
        privileged: false
  restartPolicy: Never
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs
