apiVersion: v1
kind: Pod
metadata:
  name: gtiff
spec:
  containers:
    - name: gtiff
      command:
        - "/bin/bash"
        - "-c"
        - "export RUN_FUZZER_MODE=interactive; export FUZZING_ENGINE=libfuzzer; export SANITIZER=address; export OUT=/shared/591/syntax/vr/gdal; run_fuzzer gtiff_fuzzer -jobs=200"
      image: r00tus3r/base-runner
      imagePullPolicy: Always
      stdin: true
      tty: true
      volumeMounts:
        - name: nfs
          mountPath: "/shared"
      resources:
        limits:
          cpu: "40"
          memory: 20Gi
        requests:
          cpu: "40"
          memory: 10Gi
      securityContext:
        privileged: false
  restartPolicy: Never
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs
