apiVersion: v1
kind: Pod
metadata:
  name: gtiff
spec:
  containers:
    - name: gtiff
      command:
        - "/bin/bash"
        - "-c"
        - "/shared/591/syntax/vr/gdal/run.sh"
      image: r00tus3r/base-runner
      imagePullPolicy: Always
      stdin: true
      tty: true
      volumeMounts:
        - name: nfs
          mountPath: "/shared"
      resources:
        limits:
          cpu: "40"
          memory: 60Gi
        requests:
          cpu: "40"
          memory: 50Gi
      securityContext:
        privileged: false
  restartPolicy: Never
  volumes:
  - name: nfs
    persistentVolumeClaim:
      claimName: nfs
